openapi: 3.0.0
info:
  title: Doctor Chat API
  version: 1.0.0
servers:
  - url: https://hospitalchat-production.up.railway.app

paths:
  /chat:
    post:
      summary: Send a patient message & get doctor reply
      tags: [Chat]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: string
                  format: uuid
                message:
                  type: string
      responses:
        "200":
          description: Doctor's reply
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: string

  /conversations/{conversation_id}:
    get:
      summary: Get conversation history
      tags: [Chat]
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Array of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sender:
                      type: string
                    content:
                      type: string
                    created_at:
                      type: string
                      format: date-time
